version: '3.8'
name: webstore-compose
services:
  db:
    container_name: webstore-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - webstore-db-volume:/var/lib/postgresql/data

volumes:
  webstore-db-volume:
