version: '3.4'

services:
  db:
    container_name: webstore-db
    image: postgres
    restart: always
    ports:
      - "54303:5432"
    environment:
      POSTGRES_DB: "webstore-db"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "12345"
    networks:
      - backend-net
    # volumes:
    #   - webstore-db:/var/lib/postgresql/data

  authenticationwebapi:
    container_name: authenticationwebapi
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: AuthenticationWebApi/Dockerfile
    # ports: 
    # - 8100:8080
    networks:
      - backend-net
    depends_on:
    - db

  webstoreapi:
    container_name: webstoreapi
    image: ${DOCKER_REGISTRY-}webstoreapi
    build:
      context: .
      dockerfile: WebStoreApi/Dockerfile
    # ports: 
    # - 800:8080
    networks:
      - backend-net
    depends_on:
    - db

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    ports: 
      - 7129:8081
    networks:
      - backend-net
    depends_on:
    - authenticationwebapi
    - webstoreapi

networks:
  backend-net:


# volumes:
#   webstore-db:
