version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:latest
    environment:
        - REDIS_PASSWORD=12345
    ports:
        - "6380:6379"
    networks:
      - backend-net
    volumes:
        - redisdata:/data
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user1"
      RABBITMQ_DEFAULT_PASS: "12345"
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 35s
        timeout: 35s
        retries: 35
        start_period: 35s
    networks:
      - backend-net
  db:
    container_name: webstore-db
    image: postgres
    restart: always
    ports:
      - "54303:5432"
    environment:
      POSTGRES_DB: "webstore-db"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "12345"
    networks:
      - backend-net
    volumes:
      - webstore-db:/var/lib/postgresql/data

  authenticationwebapi:
    container_name: authenticationwebapi
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: AuthenticationWebApi/Dockerfile
    networks:
      - backend-net
    depends_on:
    - db
    - rabbitmq

  webstoreapi:
    container_name: webstoreapi
    image: ${DOCKER_REGISTRY-}webstoreapi
    build:
      context: .
      dockerfile: WebStoreApi/Dockerfile
    networks:
      - backend-net
    depends_on:
    - redis
    - db
    - rabbitmq

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    ports: 
      - 7129:8081
    networks:
      - backend-net
    depends_on:
    - authenticationwebapi
    - webstoreapi

  mqreceiver:
    container_name: mqreceiver
    image: ${DOCKER_REGISTRY-}mqreceiver
    build:
      context: .
      dockerfile: MessageQueueReceiver/Dockerfile
    networks:
      - backend-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  backend-net:

volumes:
  redisdata:  
  webstore-db: